

FG_TO_SA_AREAS_ORIG

TARGET_FISHING_GROUND_CODE FISHING_GROUND_CODE PROPORTION AREA_CODE NAME_SHORT      AREA_NAME
<char>              <char>      <num>    <char>     <char>         <char>
  1:                    IRALB01             5100043          1        A1  Northwest A1 - Northwest

# Extract spatial mapping
FG_TO_SA_AREAS_ORIGIN_REV = query(DB_IOTC_MASTER(), "SELECT TARGET_CODE AS TARGET_FISHING_GROUND_CODE, SOURCE_CODE AS FISHING_GROUND_CODE, SOURCE_REL_INTERSECTION AS PROPORTION FROM refs_gis.AREA_INTERSECTIONS WHERE TARGET_CODE LIKE 'SA_ALB_0%' AND SUBSTRING(SOURCE_CODE, 1, 1) IN ('5', '6');")

# Update SA area codes
FG_TO_SA_AREAS_ORIGIN_REV[TARGET_FISHING_GROUND_CODE == "SA_ALB_01", TARGET_FISHING_GROUND_CODE := "IRALB01"]
FG_TO_SA_AREAS_ORIGIN_REV[TARGET_FISHING_GROUND_CODE == "SA_ALB_02", TARGET_FISHING_GROUND_CODE := "IRALB02"]
FG_TO_SA_AREAS_ORIGIN_REV[TARGET_FISHING_GROUND_CODE == "SA_ALB_03", TARGET_FISHING_GROUND_CODE := "IRALB03"]
FG_TO_SA_AREAS_ORIGIN_REV[TARGET_FISHING_GROUND_CODE == "SA_ALB_04", TARGET_FISHING_GROUND_CODE := "IRALB04"]

# Add information on SA areas
FG_TO_SA_AREAS_ORIGIN = merge(FG_TO_SA_AREAS_ORIGIN_REV, SA_AREAS_CONFIG, by.x = "TARGET_FISHING_GROUND_CODE", by.y = "IOTC_CODE", all.x = TRUE)



