# Color constants for current assessment areas

AR_COLOR_1 = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]

AR_COLORS = AR_COLOR_1

# Color constants for original areas

AR_ORIG_COLORS = AR_COLORS

# Color constants for current fishery groups

FG_COLORS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "BB"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "OT"])

# Color constants for current fisheries

FI_COLOR_PSFS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]
FI_COLOR_PSLS = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
FI_COLOR_BB   = ALL_FI_COLORS[FISHERY_CODE == "BB"]
FI_COLOR_OTHER= ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OTHER"]

FI_COLORS = FI_COLOR_PSFS
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PSLS)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_BB)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OTHER)