# Color constants for current assessment areas

AR_COLOR_1 = ALL_FI_COLORS[FISHERY_CODE == "GN"]
AR_COLOR_2 = ALL_FI_COLORS[FISHERY_CODE == "LLF"]
AR_COLOR_3 = ALL_FI_COLORS[FISHERY_CODE == "LIT"]
AR_COLOR_0 = ALL_FI_COLORS[FISHERY_CODE == "BB"]

AR_COLORS = AR_COLOR_1
AR_COLORS = rbind(AR_COLORS, AR_COLOR_2)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_3)
AR_COLORS = rbind(AR_COLORS, AR_COLOR_0)

# Color constants for current fishery groups

FG_COLORS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLD"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LLF"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "BB"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "LIT"])
FG_COLORS = rbind(FG_COLORS, ALL_FI_COLORS[FISHERY_CODE == "OT"])

# Color constants for current fisheries

FI_COLOR_PSFS = ALL_FI_COLORS[FISHERY_CODE == "PSFS"]
FI_COLOR_PSLS = ALL_FI_COLORS[FISHERY_CODE == "PSLS"]
FI_COLOR_LL   = ALL_FI_COLORS[FISHERY_CODE == "LLD"][, FISHERY_CODE := "LL"]
FI_COLOR_FL   = ALL_FI_COLORS[FISHERY_CODE == "LLF"][, FISHERY_CODE := "FL"]
FI_COLOR_BB   = ALL_FI_COLORS[FISHERY_CODE == "BB"]
FI_COLOR_LINE = ALL_FI_COLORS[FISHERY_CODE == "LIT"]
FI_COLOR_OTHER= ALL_FI_COLORS[FISHERY_CODE == "OT"][, FISHERY_CODE := "OTHER"]

FI_COLORS = FI_COLOR_PSFS
FI_COLORS = rbind(FI_COLORS, FI_COLOR_PSLS)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LL)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_FL)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_BB)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_LINE)
FI_COLORS = rbind(FI_COLORS, FI_COLOR_OTHER)